services:
  - type: web
    name: blooms-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://rajatkumaryadav68_db_user:<Yadav@786>@cluster0.59tplfv.mongodb.net/blooms?appName=Cluster0
      - key: PORT
        value: 8080
    healthCheckPath: /

  - type: web
    name: blooms-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://blooms-backend.onrender.com