# Server port (Render/Docker ke liye PORT env var use karega)
server.port=${PORT:8080}

# MongoDB Atlas connection
spring.data.mongodb.uri=${MONGO_URI}

# Optional: logging level
logging.level.org.springframework=INFO
logging.level.com.mongodb=INFO